### ISSUE TITLE
Specifying data point 

### ISSUE THREAD

**Issue by mschipperheyn** [masayuki0812/c3#944] opened 2015-01-27 10:35 UTC
c3.js always expects the rows and columns to match up in number of items. However, this is not always convenient, e.g. when presenting a timeseries. In this case I would like to be able to specify my time range on the x-axis and then specify points against it: ['2011-01-1',15],['2015-01-10',20], not necessarily matching the number of items on the x-axis.

I would an option that would take an array of points referencing elements available as category, as time or as otherwise as x value

    data.points:[
      ['2011-01-1',15],
      ['2015-01-10',20]
    ]

**Comment by aendrew** [comment] 2015-01-27 10:42
What specifies that it's an `x` value? Is that implicit? Why is it implicit, then?

To be honest, this seems like a difficult-to-implement edge case. If you don't have a value for a particular index, pass `null` in its place and C3 should work as intended.

Closing as `wontfix` — if you still think this is necessary, please query the [Google Group](https://groups.google.com/forum/#!forum/c3js) to see whether anyone would find this functionality useful and report back if so. I'll reopen the issue if there's sufficient demand. Thanks!

**Closed by aendrew** 2015-01-27 10:42 UTC

**Comment by mschipperheyn** [comment] 2015-01-27 10:55
Ok, well, I'm dealing with data like this

Input
2011-1-1 0 null
2011-1-7 0 null
2011-1-14 7 WLK
2011-1-14 3 GLK
2011-1-21 1 GLK
2011-1-28 0 null

GLK range
2011-1-1 0 null
2011-1-7 0 null
2011-1-14 3 GLK
2011-1-21 1 GLK
2011-1-28 0 null

WLK range
2011-1-1 0 null
2011-1-7 0 null
2011-1-14 7 WLK
2011-1-21 1 null
2011-1-28 0 null

I just find it very inconvenient to convert this input to continuous ranges for the purpose of c3.js.

I would say what specifies an x-value could be say x in the example http://c3js.org/samples/timeseries.html

or an x-axis range could also be used as a reference.
