### ISSUE TITLE
Click event not working for bar chart

### ISSUE THREAD

**Issue by mistrynilesh440** [masayuki0812/c3#1569] opened 2016-02-03 16:21 UTC
Error , Uncaught TypeError: Cannot read property 'getItem' of undefined
for new updated Google chrome 
```
 var chart = c3.generate({
				bindto: '#dvtest',
				data: {
				  columns: [ ['data1', 40, 50, 60, 70, 80] ],
				  types: { data1: 'bar'},
				  onclick: function(e) { alert(e.value); }
				}
			});	
```	``

**Comment by raphaelgera** [comment] 2016-02-04 17:02
Confirmed. Same issue with Chrome.

**Comment by raphaelgera** [comment] 2016-02-04 17:22
Duplicate of #1566

**Comment by aendrew** [comment] 2016-02-18 12:18
Closing as duplicate of #1566.

**Closed by aendrew** 2016-02-18 12:18 UTC
