### ISSUE TITLE
Using tick rotation causes chart area to disappear

### ISSUE THREAD

**Issue by savalou** [masayuki0812/c3#856] opened 2014-12-31 11:36 UTC
I'm using a Mac, latest OS, Safari and Chrome versions. I got the latest releases of d3 (3.5.3) and c3 (0.4.8).

I have long values for x-axis tick labels, so I tried to use rotate. In Safari, the bar chart renders fine the first time, but then clicking on the legend labels a couple of times makes the bars disappear. In Chrome, the bars don't show up right from the start. I have determined that changing the rotation value is the only thing that matters. Setting the value to 5, for example, only partially cuts off the bar area.

Here's my full code:
var chart = c3.generate({
	data: {
		x : 'Station',
        columns: [
["Station","Hydration Station 1","Hydration Station 2","Hydration Station 3","Hydration Station 4","Hydration Station 5","Hydration Station 6","Hydration Station 7","Hydration Station 8","Hydration Station 9","Hydration Station 10",
"Hydration Station 11","Hydration Station 12","Hydration Station 13","Hydration Station 14","Hydration Station 15","Hydration Station 16","Hydration Station 17","Hydration Station 18","Hydration Station 19","Hydration Station 20"],
["Drip Rate",2.72,1.53,1.67,1.22,0.92,0.78,1.13,1.20,2.53,1.16,2.18,1.58,1.96,1.19,1.50,1.59,0.71,1.30,1.42],
["Flow Rate",2.39,1.47,0.33,1.14,0.61,0.10,0.97,0.89,2.50,0.73,2.00,1.57,1.85,1.16,1.49,1.31,0.61,1.27,1.33,1.87],
["Loss Rate",0.00,0.00,0.00,0.02,0.03,0.03,0.03,0.03,0.04,0.05,0.06,0.06,0.07,0.08,0.10,0.10,0.12,0.12,0.12,0.13]],
        type: 'bar'
    },
	axis: {
		x: {
			type: 'category',
			tick: {
				rotate: 30,
				multiline:false
			},
		}
	}
});

**Comment by masayuki0812** [comment] 2015-01-10 14:23
Hi,
I can't reproduce this issue. Can you give us a fiddle?

**Comment by savalou** [comment] 2015-01-10 14:40
You have to resize the Result window and make it wider, you'll see.

http://jsfiddle.net/tmkwvc5y/ <http://jsfiddle.net/tmkwvc5y/>

http://jsfiddle.net/tmkwvc5y/embedded/result/ <http://jsfiddle.net/tmkwvc5y/embedded/result/>

**Comment by masayuki0812** [comment] 2015-01-17 11:55
Thank you. This issue seems already fixed in the latest code. I'll release v0.4.9 shortly, so please use it after released.

**Comment by masayuki0812** [comment] 2015-01-18 14:20
v0.4.9 has been released, so please let me close.

**Closed by masayuki0812** 2015-01-18 14:20 UTC
Labels: bug, resolved maybe
