### ISSUE TITLE
Additinal y axis is limited to 1

### ISSUE THREAD

**Issue by VishalAdPushup** [masayuki0812/c3#852] opened 2014-12-29 11:43 UTC
I am trying to show multiple series on spline chart, The data in all series has great difference and thus if I use single y axis, series with smaller data sets drops down to x axis and series with larger data is shown properly.

I tried adding additional y axis, but found that it is limited to 1, Is there any way by which I can get what I want.

**Comment by masayuki0812** [comment] 2015-01-10 12:38
Hi,  This is a duplicate of #112 , so please let me close. Thanks!

**Closed by masayuki0812** 2015-01-10 12:38 UTC

**Comment by VishalAdPushup** [comment] 2015-01-12 14:18
Hi, Thank you for the feedback, I would love to contribute if you can help me with basic details to speed up.
