### ISSUE TITLE
multiple Y axis

### ISSUE THREAD

**Issue by nitin0708** [masayuki0812/c3#1070] opened 2015-03-20 07:14 UTC
Hi

Can we add multiple Y axis at one side of the graph?

Thanks & Regards,
Nitin Goyal

**Comment by jmnunezizu** [comment] 2015-03-20 10:01
Hi,

You can have 2 Y axis. Have a look at this example: http://c3js.org/samples/axes_y2.html

Cheers,
Jose.-

**Comment by nitin0708** [comment] 2015-03-20 10:07
Hi,
I saw this one example but i am trying this two axes should be same side.

Thanks and Regards,
Nitin

**Comment by jmnunezizu** [comment] 2015-03-20 10:52
Hi @nitin0708,

Wouldn't that be confusing? I don't recall seeing a chart with 2 Y axis on the same side. What would be the problem with using a left Y axis and a right Y axis?

Cheers,
Jose.-

**Comment by nitin0708** [comment] 2015-03-20 10:58
Hi, 
I can use more than two relation in a graph so i am trying to use different-different y axis.

Thanks and Regards,
Nitin

**Comment by nitin0708** [comment] 2015-03-20 11:04
![screenshot from 2015-03-20 16 29 51](https://cloud.githubusercontent.com/assets/10219173/6750281/b399f764-cf1e-11e4-87d5-013eb162c604.png)

in above example i am using three level so i am trying to show different y axis for different level.

Thanks and regards,
Nitin

**Comment by jmnunezizu** [comment] 2015-03-20 11:25
So you have 3 series on the X axis, and you want to have 3 Y axis for each one of the series, correct?
Let me ask you this: if you do have 3 Y axis, how would you compare the series, given that they'd be in different scales?

I'm sorry I cannot help, but I've never seen something like this.

Cheers,
Jose.-

**Comment by nitin0708** [comment] 2015-03-20 11:36
![screenshot from 2015-03-20 17 02 12](https://cloud.githubusercontent.com/assets/10219173/6750719/347628f4-cf23-11e4-91e4-0edf3cae6fec.png)

in above screenshot 4 axis is present.so is it possible in c3 js??

Thanks and regards,
Nitin

**Comment by jmnunezizu** [comment] 2015-03-20 12:07
Hi @nitin0708 – I'm sorry to say, but as far as I know you can only have 2 Y axis: left and right.

**Comment by nitin0708** [comment] 2015-03-20 13:22
Hi,
![screenshot from 2015-03-20 18 46 54](https://cloud.githubusercontent.com/assets/10219173/6752146/d7312a7c-cf31-11e4-95ac-acee3ff690bb.png)

the y label is not showing properly if length of label is more.is there any solution of increasing width??

Thanks and Regards,
Nitin

**Comment by jmnunezizu** [comment] 2015-03-20 14:37
Perhaps you could try increasing the size of the chart or the parent container?

**Comment by philliproso** [comment] 2015-04-16 19:11
I have also seen a need for this. It is often important when analyzing multiple time-series. But there are better ways. 

One option I can think of is to just scale the data using zscore eg (x=(x-mean(x))/(var(x)). Then hide the axis and have the actual data in the tooltips.  This allows people to view the time related correlation between the variables and be aware of the actual size of the data when needed. Data ranges can be displayed separately. 

 I am going to give my hand at packing this into an angular linked app, will see if I can post an example afterwards. But the main thing is there might be better user experience solutions to displaying multiple axis which can be confusing.

**Comment by sam-g-steel** [comment] 2015-05-06 18:52
philliproso, did you have any luck with your idea for representing multi-y axis data?
I need to do the same thing and would love to know how your experiment worked out.

**Comment by gnomeontherun** [comment] 2015-05-11 19:49
This would be useful, mostly so that you can have 3+ series with different units or scales. We have a need to display 3 series that have vastly different scales, which do not adequately display the variance on the same axis.

**Comment by jwair** [comment] 2015-06-11 06:01
Any luck with the 3+ y axis? I have 3 time series data that I want to represent on the same chart (very different y ranges and units). Is there a way to do that with C3?
Thanks

**Comment by cfigueiredo** [comment] 2015-10-09 10:04
Any news on this 3+ y-axis feature?

**Comment by otisg** [comment] 2015-10-30 01:35
Is this a dupe of #112?

**Comment by aendrew** [comment] 2015-12-04 20:29
This is definitely a dupe of #112. Closing.

**Closed by aendrew** 2015-12-04 20:29 UTC

**Comment by abhishek-g** [comment] 2017-04-07 08:40
HI @aendrew  any update on this , as the other link is closed for this discussion
