### ISSUE TITLE
Using c3 with polymer ?

### ISSUE THREAD

**Issue by antoineDeRengerve** [masayuki0812/c3#1035] opened 2015-02-27 08:31 UTC
I want to display charts in a polymer (https://www.polymer-project.org/) framework.

I managed to display a line chart but there are pbs : 
* It looks like the fill property of svg objects is active because I have a black area enclosed by the line chart. Maybe I fail to load correctly the css file ?
![snapshot_c3chart_trouble_with_polymer](https://cloud.githubusercontent.com/assets/10978052/6409310/04c2150e-be62-11e4-9f24-26f96a46b7aa.png)

* More critically, any update of the chart (tooltip, etc.), generate some transient elements at root level (all elements generated by the chart should remain in the shadow root of the element containing the chart). These transient elements disturb the overall framework design by generating strange resizes of other elements.

Has anyone tried to combine c3 and polymer ? 
Is there a good (and simple) way to do it ? 
If not, is it planned as an enhancement of c3 ?

**Comment by aendrew** [comment] 2015-02-27 11:17
![relevant](http://i3.kym-cdn.com/photos/images/original/000/019/239/128875590863673614.jpg)

I'm using Polymer a boatload at the moment and never thought to try creating a c3-chart element. I might give it a go this afternoon and share my experiences.

**Comment by aendrew** [comment] 2015-02-27 12:19
Okay, so I've made aendrew/c3-chart for this purpose. Didn't have any problems, though I'm having a bit of an issue ensuring C3 and D3 have loaded before firing domReady. 

Demo: http://aendrew.com/c3-chart/components/c3-chart/demo.html

I haven't noticed any elements in the root and it seems to work as intended. Issue you're having with axes above is due to the CSS not loading properly before.

Seems to work as intended, so closing. If you're still having problems after looking at my example code, do let me know and I'll reopen. Thanks! :smile:

**Closed by aendrew** 2015-02-27 12:19 UTC

**Comment by adamtysonsmith** [comment] 2016-05-15 13:05
Its all good if you are generating a line chart, but for different chart types (bar, pie) they always render as a line chart.. This is puzzling and I have no idea why using Polymer would break that functionality??

**Comment by adamtysonsmith** [comment] 2016-05-15 13:08
@aendrew Were you able to get different chart types working using your code above?  Here is the code I am using:

`Polymer({
  is: 'chart-bar',
  properties: {
    chartId: String
  },
  ready: onReady
});

function onReady() {
  drawChart.call(this);
}


function drawChart() {
  var id = '#' + this.chartId;
  
  var chart = c3.generate({
    bindto: this.$$(id),
    data: {
      columns: [
        ['data1', 30, 200, 100, 400, 150, 250],
        ['data2', 50, 20, 10, 40, 15, 25]
      ],
      type: 'bar' 
    },
    size: {
      width: 800,
      height: 300
    }
  });
}`

**Comment by adamtysonsmith** [comment] 2016-05-15 13:54
Update:
Got this to work with different chart types, apparently Polymer does not like it when you use .call() in the ready function.  This code works for different chart types:

```
Polymer({
  is: 'chart-bar',
  properties: {
    chartId: String
  },
  ready: onReady,
  drawChart: drawChart
});


function onReady() {
  this.drawChart();
}


function drawChart() {
  var id = '#' + this.chartId;

  var chart = c3.generate({
    bindto: this.$$(id),
    data: {
      columns: [
        ['data1', 30, 200, 100, 400, 150, 250],
        ['data2', 50, 20, 10, 40, 15, 25]
      ],
      type: 'bar' 
    },
    size: {
      width: 800,
      height: 300
    }
  });
}
```
