### ISSUE TITLE
Chrome 48 removes SVGPathSeg and SVGPathSegList APIs

### ISSUE THREAD

**Issue by adufilie** [masayuki0812/c3#1565] opened 2016-01-29 16:36 UTC
See https://www.chromestatus.com/feature/5708851034718208
I've created a pull request with the fix: https://github.com/masayuki0812/c3/pull/1564

**Comment by aendrew** [comment] 2016-02-18 12:36
Duplicate of #1566.

**Closed by aendrew** 2016-02-18 12:36 UTC
