### ISSUE TITLE
"Cannot read property 'getItem' of undefined" when using bar chart when selection is enabled

### ISSUE THREAD

**Issue by varunoberoi** [masayuki0812/c3#1529] opened 2016-01-05 08:04 UTC
Hi folks

I am trying to enable selection on bar charts like so:
    
```javascript
    data: {
       columns: [            
          ['data2', 130, 100, 140, 200, 150, 50]
       ],
       type: 'bar',
         selection: {
            enabled: true
         }
    }
```

This gives following error, when hovered upon:
         
        Cannot read property 'getItem' of undefined

Here is the link to the fiddle:
https://jsfiddle.net/varunoberoi/Lo0onqtm/

Is there any workaround ?

**Comment by varunoberoi** [comment] 2016-01-06 11:16
Ok so after some digging I found that this issue started coming all of sudden because chrome has removed deprecated 'path.pathSegList' api from their latest(beta) version. I hope you guys upgrade to svg2 apis soon. Meanwhile a quick fix is to use a polyfill eg:

https://github.com/progers/pathseg

**Comment by aendrew** [comment] 2016-02-18 12:52
Duplicate of #1566.

**Closed by aendrew** 2016-02-18 12:52 UTC
