### ISSUE TITLE
Chart caption

### ISSUE THREAD

**Issue by skullcrasher** [masayuki0812/c3#102] opened 2014-03-31 14:33 UTC
Is there a possibility to set the caption for the whole chart (not the x/y axis)?
So it shows the caption above/under the chart?
Just similar to a figure caption in latex, to describe the chart.

**Comment by aendrew** [comment] 2015-07-10 10:41
Closing as a duplicate of #1021.

**Closed by aendrew** 2015-07-10 10:41 UTC
Labels: enhancement
