### ISSUE TITLE
y axis label overlap only in IE

### ISSUE THREAD

**Issue by mvolkmann** [masayuki0812/c3#969] opened 2015-02-02 20:51 UTC
See the attached image. This is happening for me in IE11, but not in Chrome.
![overlap](https://cloud.githubusercontent.com/assets/79312/6008938/f72dac44-aaea-11e4-88cd-74f5d7ad3145.png)

**Comment by mattdh666** [comment] 2015-02-04 17:05
For me, this happens in Chrome, Safari, and Firefox.

When I use the both **padding.left** and **axis.y.label** options, the y-axis label overlaps the y-axis tick mark labels.

Here's an example:  http://jsfiddle.net/mattdh666/7u6kjeo7/

If you resize the jsfiddle window wider than its original size, the Y label will 'pop' out and be correct and persist. (Setting y axis padding or padding on the entire graph doesn't help.)

![screen shot 2015-01-21 at 11 24 39 am](https://cloud.githubusercontent.com/assets/4089083/6045023/ef1e1aa4-ac4b-11e4-8b52-be1603d8bfe9.png)

This issue should be renamed to reflect that the problem isn't only with IE.

**Comment by joshclow** [comment] 2015-02-04 22:51
I think there may be two different issues here, then.

What I see in IE is that the dy value on the axis text (when the position is set to outside) is set to -20, which is what I'd expect to come out of c3_chart_internal_fn.dyForYAxisLabel if getMaxTickWidth('y') is coming back as 0. This behavior occurs on IE independent of setting a padding.left value and doesn't correct on resize.

**Comment by mattdh666** [comment] 2015-02-05 19:25
In my situation (not on IE but with **padding.left**), the dy attribute on the y-axis label text is also set to -20, since in dyForYAxisLabel, the call to getMaxTickWidth('y') is also returning 0.

**Comment by joshclow** [comment] 2015-02-06 05:04
So if I'm reading through this right, getMaxTickWidth won't recompute tick widths at all when the bounding box of the tick/labels has a left edge <0. On Chrome, when things are working, it looks to me like there's a point in c3_chart_internal_fn.updateSizeForLegend where the bounding boxes are far enough to the right to trigger the recompute when getMaxTickWidth gets called during that function, but then later, they presumably get translated left into their final position, at which point getMaxTickWidth stops looking at them.
I'm trying to follow through on IE, but the evidence suggests that this math never happened, because whenever I hit getMaxTickWidth there, the cached values in $$.currentMaxTickWidths are all zero, and the label bounding boxes all have .left < 0.

**Comment by joshclow** [comment] 2015-02-06 05:18
Yeah, this seems to be the big difference in the IE case...it doesn't look like there's ever a time where the bounding boxes on the tick labels have a left edge > 0, where in Chrome and Safari they do on one layout pass.

**Comment by ve3** [comment] 2015-02-23 11:13
For me, IE did not display full Y axis.
Example: full text of Y axis is
400
350
300
250
200
150
100
50
0

But IE 9 to IE 11 display like this.
00
50
00
50
00
50
00
50
0

**Comment by Manjunath-Siddappa** [comment] 2015-02-26 08:50
Same Issue here.

![ie9 - y axis](https://cloud.githubusercontent.com/assets/8860807/6388417/c27eb5aa-bdbf-11e4-9a9c-b1a554563ca2.jpg)

Please let me know how to resolve this.

**Comment by ve3** [comment] 2015-02-26 09:42
add padding to fix this.

```
padding: {
    left: 40,// require to fix IE overflow and hidden
},
```
The full code is
```
var chart = c3.generate({
    bindto: '#chart',
    data: {
        // your data
    },
    padding {
        left: 40
        // all padding available are top, right, left, bottom
    }
});
```

**Comment by Manjunath-Siddappa** [comment] 2015-02-26 09:47
@ve3  I tried it, it will affect other browsers.

If i use this ,i am getting space in chrome and firefox.

**Comment by masayuki0812** [comment] 2015-03-08 08:10
Sorry, this is a bug I made in `v0.4.9`. It's been fixed by this commit https://github.com/masayuki0812/c3/commit/4140ceb2fca1aae1e3da95d9984639d0980d29df and already released in `v0.4.10-rc2`. Also, this seems a duplicate of https://github.com/masayuki0812/c3/issues/961 .

For IE issue, let me give some time. I'll look into.

**Comment by Manjunath-Siddappa** [comment] 2015-03-10 10:59
Thank you.

i Appreciate it.

**Comment by masayuki0812** [comment] 2015-03-17 12:43
`0.4.10` has been released and it seems working on IE as well, so let me close at the moment.

@Manjunath-Siddappa If this issue is still happening on IE, please let me know.

**Closed by masayuki0812** 2015-03-17 12:43 UTC
Labels: bug

**Comment by Manjunath-Siddappa** [comment] 2015-03-18 05:03
@masayuki0812  thank you, now it is working in a IE9.

"good job! ... Keep up the good work
