### ISSUE TITLE
Zoom is not working with touch devices

### ISSUE THREAD

**Issue by sidiee** [masayuki0812/c3#1331] opened 2015-08-18 18:19 UTC
Hi I tried implementing pinch zoom on touch devices but was unable to do that.
Please can you provide your inputs ? 

Thanks,
Siddharth

**Comment by j-schumann** [comment] 2015-08-19 10:44
Duplicate of #1300
Please close this issue if you agree and post your problem description there.

**Closed** 2015-08-23 19:34 UTC
