### ISSUE TITLE
Radius function data changes

### ISSUE THREAD

**Issue by pareeohnos** [masayuki0812/c3#915] opened 2015-01-19 19:39 UTC
I've run into an issue that's causing the data supplied to the radius function I use to change after a data item has been clicked.

I'm really struggling to figure out where in the code it's happening and am having no luck figuring out what's going on but I'm considering the idea that it is a bug.

I have the following simple function for my radius

    point: {
      r: function(item) {
        var val = item.value;
        console.log(item);

        if (val === null || val === undefined || val === 0) {
          return 0;
        } else {
          return 4.5;
        }
      }
    }

When the page first loads the console output looks as expected, with the items outputting as something like

    Object {x: Wed Jan 01 2014 00:00:00 GMT+0000 (GMT), value: 100, id: "Name", index: 0, name: "Name"}

This is what I'm expecting. What's happening however, is when I click on a point, the radius function is then supplied something that looks like this

    Object {id: "Name", id_org: "Name", values: Array[1002]}

My function then returns 0 and the point effectively disappears.

I added a debugging output to the on click event to inspect the data item there, and the data hasn't changed and is passed to that function correctly, but is broken for the radius function.

Looking through the `c3` code it seems that the `id_org` is generated for use with caching, or the `convertDataToTargets` method. Is this meant to be used by the radius or is this a bug?

If intentional, how can I then get the individual data item I want in the radius function? It feels like a bug given the argument supplied completely changes form, making any code relying on it unstable.

**Comment by masayuki0812** [comment] 2015-01-25 06:35
Hi, can you provide a fiddle? I can't reproduce this case, I mean I don't see this even if I click the points:
```
Object {id: "Name", id_org: "Name", values: Array[1002]}
```
And which version of c3 are you using?

**Comment by pareeohnos** [comment] 2015-01-26 10:06
hmm I can't seem to replicate this now :( not a clue what's going on but I'll keep digging and update later.

**Comment by pareeohnos** [comment] 2015-01-26 18:53
ok I've managed to reproduce it. It seems as though it comes into play when I specify different chart types.

The code I'm working with allows the user to customise how many charts are rendered, and what type of chart they are. Originally when the charts loaded, I had hard coded the type that they started with and never had a problem, however I then changed it so that the type could be configured at load time. This then introduced the error shown in this fiddle:

http://jsfiddle.net/rsgLezgy/

This fiddle sets up 3 charts: one scatter, one area, and one line. If you click on any point, it will then disappear. I've got a console log output so you can see the invalid data output. By simply commenting out the line `types: types.types,` the points will no longer disappear.

I hope this is enough information. Let me know if you need any more.

**Comment by masayuki0812** [comment] 2015-02-09 03:11
Thank you for the fiddle. After some investigations, I found the data bound to the element clicked was changed unexpectedly. I don't know the reason (it seems a kind of bug related to `select`), but fixed by using `selectAll` instead.
I will release this fix in the next version v0.4.9. Thanks.

**Comment by pareeohnos** [comment] 2015-02-09 09:32
Amazing thanks :D

**Comment by pareeohnos** [comment] 2015-02-24 15:13
Just tried v0.4.9 but the issue is still there. I updated the fiddle (http://jsfiddle.net/8kxtyoe6/) with the new version and it is still replicating the issue

**Comment by masayuki0812** [comment] 2015-03-10 12:06
I can see this issue seems not happening anymore in v0.4.10-rc4 (the latest version) as you can see here: http://jsfiddle.net/8kxtyoe6/1/

**Comment by pareeohnos** [comment] 2015-03-10 18:06
Perfect! That's working now. Thank you :smile:

**Comment by masayuki0812** [comment] 2015-03-17 12:19
`0.4.10` has been released, so let me close. Thanks!

**Closed by masayuki0812** 2015-03-17 12:19 UTC
Labels: bug, resolved maybe

**Comment by mjncoder** [comment] 2020-02-29 02:39
Hi, it seems this bug is still an issue.  I am using version 0.7.15 and am having the exact issue described by the original post.
