### ISSUE TITLE
regions API is broken

### ISSUE THREAD

**Issue by amutake** [masayuki0812/c3#1174] opened 2015-05-20 10:10 UTC
Thank you for nice library.

I found a bug in regions API.

When using regions API and the number of elements of its argument is less then the previous one, wrong region disappear.

```javascript
var chart = c3.generate({
    bindto: '#chart',
    data: {
        columns: [
            ['data', 1, 3, 2, 4, 3]
        ]
    },
    // 2 regions
    regions: [
        { axis: 'x', start: 0, end: 2, class: 'over' },
        { axis: 'x', start: 3, end: 4, class: 'over' }
    ]
});

setTimeout(function() {
    // switch to 1 region
    chart.regions([
        { axis: 'x', start: 3, end: 4, class: 'over' }
    ]);
}, 1000); 
// => the region of {start: 3, end: 4} disapper
```

I tried with the following versions.

- D3: 3.5.5
- C3: 0.4.10

The full example is available at http://jsfiddle.net/34uo9p5z/

**Comment by mmiszy** [comment] 2015-06-01 13:20
Isn't C3 only compatible with D3 <=3.5.0 ?

**Comment by aendrew** [comment] 2015-08-07 16:45
Duplicate of #1255.

**Closed by aendrew** 2015-08-07 16:45 UTC
