### ISSUE TITLE
How to add error bar chart in to C3JS ?

### ISSUE THREAD

**Issue by mistrynilesh440** [masayuki0812/c3#1022] opened 2015-02-24 14:25 UTC
I have three types of values available(higher,medium and lower). Can you please help out how to add this chart in to existing architecture ? Thanks in advance.

![images](https://cloud.githubusercontent.com/assets/11177229/6351140/10880cf4-bc5f-11e4-9e0b-36a3f7895c6d.jpg)

**Comment by masayuki0812** [comment] 2015-05-10 12:43
This is a duplicate of #253 , so let me close.

**Closed by masayuki0812** 2015-05-10 12:43 UTC
