### ISSUE TITLE
Is there any function to put chart title?

### ISSUE THREAD

**Issue by udhaya2kmrv** [masayuki0812/c3#859] opened 2015-01-02 08:40 UTC
Is there any function to put title in inside chart element(in svg element)

**Comment by masayuki0812** [comment] 2015-01-11 02:18
Unfortunately not. And this is a duplicate of #102 , so please let me close.

**Closed by masayuki0812** 2015-01-11 02:18 UTC

**Comment by aendrew** [comment] 2015-07-10 10:42
Work on this is now is #1021, anyone arriving at this issue from where-ever.
