### ISSUE TITLE
Categories for bar charts?

### ISSUE THREAD

**Issue by jonlachlan** [masayuki0812/c3#925] opened 2015-01-21 08:23 UTC
All of the examples seem to only use numeric values for the x-axis on bar charts. This would mean that any categories would need to be series that have their own legend entry. But what about when I want to have a custom text label in the x-axis, and only one series (and therefore only one color)?

I have tried including axis.x.type='category', but it only shows '0' in the x-axis (since my 2D column-oriented array has only one array element at the higher level, i.e., the array index is 0.

**Comment by propagated** [comment] 2015-01-21 15:49
@jonlachlan i'm going to jump on your issue here because i'm also having issues with bar charts and categories as well. See my fiddle for a working example of a bar chart with categories.  

To see my issues with bar charts and categories, see this fiddle: 
http://jsfiddle.net/propagated/1uuj8bdd/  

When i call load() with new data it truncates my x-axis rather than add new values to it. If you look at my generate() code, you'll see i have commented out `axis.x.type= 'timeseries'`.  
If you uncomment that and comment out `axis.x.type = 'categories'` you'll see the behavior on the x-axis that i want, however a timeseries bar-chart looks awful for this data.

**Comment by jonlachlan** [comment] 2015-01-21 16:21
Thanks for your working example. I modified to ```axis.x.type = 'category'``` and yes it does indeed work. This shows me that I probably have a problem with my data and axis definition.
I see that there's possibly a problem with the timeseries axis. I played around with your code a little, and found an odd behavior: Try changing the first date value in ```initx``` from ```'2013-10-31'``` to ```'2013-09-31'```. Change it back from ```'category'``` to ```'timeseries'```. When you run this, the first x axis value will be 10/01/13 upon loading the new data, instead of the expected 10/09/13.

**Comment by masayuki0812** [comment] 2015-01-25 12:10
The datetime issue you wrote is the expected behavior. Please try `new Date('2013-09-31')`. I think you should get `Tue Oct 01 2013 09:00:00 GMT+0900 (JST)`. So, I mean `10/01/13` you get in your code is correct.

Btw, please let me close this issue because it's not a bug and please ask in GoogleGroup first as you can see here https://github.com/masayuki0812/c3#using-the-issue-queue Thanks.

**Closed by masayuki0812** 2015-01-25 12:10 UTC
